site_name: Dokumentacja języka polskiego
site_description: Materiały dydaktyczne do nauki gramatyki języka polskiego
site_url: ""

theme:
  name: material
  language: pl
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Włącz tryb ciemny
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Włącz tryb jasny

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      lang: pl

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Start: index.md
  - Gramatyka:
      - Przegląd: gramatyka/index.md
      - Podstawy gramatyki: gramatyka/podstawy/index.md
      - Części mowy:
          - Przegląd: gramatyka/czesci-mowy/index.md
          - Czasownik: gramatyka/czesci-mowy/czasownik/index.md
          - Przymiotnik: gramatyka/czesci-mowy/przymiotnik/index.md
          - Rzeczownik: gramatyka/czesci-mowy/rzeczownik/index.md
          - Zaimki: gramatyka/czesci-mowy/zaimki/index.md
      - Fleksja: gramatyka/fleksja/index.md
      - Składnia: gramatyka/skladnia/index.md
      - Słowotwórstwo: gramatyka/slowotworstwo/index.md
  - Czytanie i analiza w praktyce:
      - Wprowadzenie: praktyka/index.md
      - Tajemnica Szklanego Lasu: praktyka/interaktywna-analiza-czesci-mowy.md
  - Materiały dodatkowe: materialy-dodatkowe/index.md
  - Archiwum PDF: pdf/index.md
