site_name: Dokumentacja języka polskiego
site_description: Materiały do nauki gramatyki języka polskiego
site_url: ""

theme:
  name: readthedocs
  language: pl

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Start: index.md
  - Gramatyka:
      - Wprowadzenie: gramatyka/index.md
      - Zagadnienia:
          - Czasownik: gramatyka/czasownik/index.md
          - Przymiotnik: gramatyka/przymiotnik/index.md
          - Rzeczownik: gramatyka/rzeczownik/index.md
          - Zaimki: gramatyka/zaimki/index.md
  - Materiały dodatkowe: materialy-dodatkowe/index.md
