window.SZKLANY_LAS_STORY = [
  [
    {t:"W",p:"preposition"},{t:"małej",p:"adjective"},{t:"wiosce",p:"noun"},{t:"pod",p:"preposition"},{t:"górami",p:"noun"},{t:"mieszkała",p:"verb"},{t:"odważna",p:"adjective"},{t:"dziewczynka",p:"noun"},{t:"Lena",p:"noun",a:"."}
  ],
  [
    {t:"Każdego",p:"pronoun"},{t:"ranka",p:"noun"},{t:"ona",p:"pronoun"},{t:"zanosiła",p:"verb"},{t:"świeży",p:"adjective"},{t:"chleb",p:"noun"},{t:"staremu",p:"adjective"},{t:"strażnikowi",p:"noun"},{t:"mostu",p:"noun",a:"."}
  ],
  [
    {t:"Pewnego",p:"pronoun"},{t:"dnia",p:"noun"},{t:"strażnik",p:"noun"},{t:"pokazał",p:"verb"},{t:"jej",p:"pronoun"},{t:"srebrny",p:"adjective"},{t:"klucz",p:"noun"},{t:"oraz",p:"conjunction"},{t:"tajemniczą",p:"adjective"},{t:"mapę",p:"noun",a:"."}
  ],
  [
    {t:"Na",p:"preposition"},{t:"mapie",p:"noun"},{t:"cienka",p:"adjective"},{t:"droga",p:"noun"},{t:"biegła",p:"verb"},{t:"prosto",p:"adverb"},{t:"do",p:"preposition"},{t:"Szklanego",p:"adjective"},{t:"Lasu",p:"noun",a:"."}
  ],
  [
    {t:"Nikt",p:"pronoun"},{t:"z",p:"preposition"},{t:"mieszkańców",p:"noun"},{t:"nie",p:"particle"},{t:"chciał",p:"verb"},{t:"tam",p:"adverb"},{t:"wchodzić",p:"verb"},{t:"po",p:"preposition"},{t:"zachodzie",p:"noun"},{t:"słońca",p:"noun",a:"."}
  ],
  [
    {t:"Lena",p:"noun"},{t:"schowała",p:"verb"},{t:"klucz",p:"noun"},{t:"do",p:"preposition"},{t:"kieszeni",p:"noun"},{t:"i",p:"conjunction"},{t:"wyruszyła",p:"verb"},{t:"samotnie",p:"adverb"},{t:"przed",p:"preposition"},{t:"siebie",p:"pronoun",a:"."}
  ],
  [
    {t:"W",p:"preposition"},{t:"lesie",p:"noun"},{t:"wysokie",p:"adjective"},{t:"drzewa",p:"noun"},{t:"odbijały",p:"verb"},{t:"księżyc",p:"noun"},{t:"jak",p:"conjunction"},{t:"tysiące",p:"numeral"},{t:"luster",p:"noun",a:"."}
  ],
  [
    {t:"Między",p:"preposition"},{t:"nimi",p:"pronoun"},{t:"przemykały",p:"verb"},{t:"małe",p:"adjective"},{t:"światła",p:"noun",a:","},{t:"ale",p:"conjunction"},{t:"żadne",p:"pronoun"},{t:"nie",p:"particle"},{t:"zbliżało",p:"verb"},{t:"się",p:"pronoun"},{t:"do",p:"preposition"},{t:"niej",p:"pronoun",a:"."}
  ],
  [
    {t:"Nagle",p:"adverb"},{t:"z",p:"preposition"},{t:"ciemnej",p:"adjective"},{t:"ścieżki",p:"noun"},{t:"wyszedł",p:"verb"},{t:"biały",p:"adjective"},{t:"wilk",p:"noun"},{t:"z",p:"preposition"},{t:"błękitnymi",p:"adjective"},{t:"oczami",p:"noun",a:"."}
  ],
  [
    {t:"On",p:"pronoun"},{t:"nie",p:"particle"},{t:"warczał",p:"verb",a:","},{t:"tylko",p:"particle"},{t:"spokojnie",p:"adverb"},{t:"położył",p:"verb"},{t:"przed",p:"preposition"},{t:"nią",p:"pronoun"},{t:"złoty",p:"adjective"},{t:"liść",p:"noun",a:"."}
  ],
  [
    {t:"Na",p:"preposition"},{t:"liściu",p:"noun"},{t:"widniał",p:"verb"},{t:"krótki",p:"adjective"},{t:"napis",p:"noun",a:":"},{t:"Otwórz",p:"verb"},{t:"bramę",p:"noun"},{t:"zanim",p:"conjunction"},{t:"obudzi",p:"verb"},{t:"się",p:"pronoun"},{t:"król",p:"noun"},{t:"cieni",p:"noun",a:"."}
  ],
  [
    {t:"Dziewczynka",p:"noun"},{t:"pobiegła",p:"verb"},{t:"za",p:"preposition"},{t:"wilkiem",p:"noun"},{t:"i",p:"conjunction"},{t:"dotarła",p:"verb"},{t:"do",p:"preposition"},{t:"kamiennej",p:"adjective"},{t:"wieży",p:"noun",a:"."}
  ],
  [
    {t:"Jej",p:"pronoun"},{t:"drzwi",p:"noun"},{t:"były",p:"verb"},{t:"ciężkie",p:"adjective",a:","},{t:"lecz",p:"conjunction"},{t:"srebrny",p:"adjective"},{t:"klucz",p:"noun"},{t:"pasował",p:"verb"},{t:"idealnie",p:"adverb",a:"."}
  ],
  [
    {t:"W",p:"preposition"},{t:"środku",p:"noun"},{t:"ogromny",p:"adjective"},{t:"zegar",p:"noun"},{t:"odmierzał",p:"verb"},{t:"ostatnie",p:"adjective"},{t:"minuty",p:"noun"},{t:"przed",p:"preposition"},{t:"północą",p:"noun",a:"."}
  ],
  [
    {t:"Lena",p:"noun"},{t:"zobaczyła",p:"verb"},{t:"czarną",p:"adjective"},{t:"koronę",p:"noun"},{t:"i",p:"conjunction"},{t:"zrozumiała",p:"verb"},{t:"plan",p:"noun"},{t:"ukrytego",p:"adjective"},{t:"władcy",p:"noun",a:"."}
  ],
  [
    {t:"To",p:"pronoun"},{t:"on",p:"pronoun"},{t:"wysyłał",p:"verb"},{t:"cienie",p:"noun"},{t:"aby",p:"conjunction"},{t:"przestraszyć",p:"verb"},{t:"ludzi",p:"noun"},{t:"i",p:"conjunction"},{t:"zdobyć",p:"verb"},{t:"dolinę",p:"noun",a:"."}
  ],
  [
    {t:"Ona",p:"pronoun"},{t:"podniosła",p:"verb"},{t:"koronę",p:"noun",a:","},{t:"lecz",p:"conjunction"},{t:"wilk",p:"noun"},{t:"natychmiast",p:"adverb"},{t:"uderzył",p:"verb"},{t:"w",p:"preposition"},{t:"nią",p:"pronoun"},{t:"łapą",p:"noun",a:"."}
  ],
  [
    {t:"Korona",p:"noun"},{t:"pękła",p:"verb",a:","},{t:"a",p:"conjunction"},{t:"z",p:"preposition"},{t:"jej",p:"pronoun"},{t:"wnętrza",p:"noun"},{t:"uleciał",p:"verb"},{t:"czerwony",p:"adjective"},{t:"dym",p:"noun",a:"."}
  ],
  [
    {t:"Wtedy",p:"adverb"},{t:"wszystkie",p:"pronoun"},{t:"lustra",p:"noun"},{t:"rozbłysły",p:"verb"},{t:"i",p:"conjunction"},{t:"pokazały",p:"verb"},{t:"prawdziwą",p:"adjective"},{t:"drogę",p:"noun"},{t:"do",p:"preposition"},{t:"domu",p:"noun",a:"."}
  ],
  [
    {t:"Biały",p:"adjective"},{t:"wilk",p:"noun"},{t:"przemienił",p:"verb"},{t:"się",p:"pronoun"},{t:"w",p:"preposition"},{t:"młodego",p:"adjective"},{t:"księcia",p:"noun",a:","},{t:"którego",p:"pronoun"},{t:"więziła",p:"verb"},{t:"stara",p:"adjective"},{t:"magia",p:"noun",a:"."}
  ]
];
